# Generated by Django 4.0.2 on 2022-03-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_11', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project_name',
        ),
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
    ]
